### PR TITLE
Downgrade `eslint-plugin-promise` to `^6.6.0`

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Downgrade `eslint-plugin-promise` and ignore future updates until `eslint-config-standard` bumps the major version of it's `eslint-plugin-promise` dependency

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix user

```

### CODE REVIEW

**Comment by holgerkoser** [comment]
That is what I have already prepared. The package `eslint-config-standard` is not maintained and needs to be replaced by [neostandard](https://github.com/neostandard/neostandard/blob/main/README.md). This includes `eslint-plugin-promise` and supports flatconfig.

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Comment by holgerkoser** [comment]
See PR https://github.com/gardener/dashboard/pull/2137

**Comment by petersutter** [comment]
> That is what I have already prepared. The package `eslint-config-standard` is not maintained and needs to be replaced by [neostandard](https://github.com/neostandard/neostandard/blob/main/README.md). This includes `eslint-plugin-promise` and supports flatconfig.

nice!

**Pull request merged**
