### PR TITLE
Use Clipboard API

### LINKED ISSUE #1341: Copy button does not work
**What happened**:
The copy button for the kubeconfig, gardenctl target command does not work on the cluster access dialog, however it works on the shoot details page
Screenshot 2022-11-11 at 11 13 05

**What you expected to happen**:
kubeconfig / target command content should be in the clipboard

**How to reproduce it (as minimally and precisely as possible)**:
- Navigate to the shoot list
- Click on the key symbol of any cluster
- Click any copy button

**Anything else we need to know**:

**Workaround**:
Navigate to the shoot details and use the copy buttons there

**Environment**:

### PR DESCRIPTION
**Pull request by holgerkoser**
**What this PR does / why we need it**:
Due to a [change](https://github.com/vuetifyjs/vuetify/commit/89e3850c5478c7bf0ae6081a95f6d2b39e690e8f) in vuetify the clipboard javascript library does not work anymore when using inside of `v-dialog`. With this PR we have removed this library and directly use the new browser API [navigator.clipboard.writeText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) to copy data into the clipboard. The first time this API is used the user now has to confirm that the website is allowed to access the system clipboard. 

**Which issue(s) this PR fixes**:
Fixes #1341 

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed a problem that occurs on the cluster access dialog when trying to copy kubeconfig or target command content  into the clipboard. This regression was introduced with release 1.62.0.
```

### CODE REVIEW

**Comment by petersutter** [comment]
also remove `"clipboard": "^2.0.11",` from `package.json`

**Comment by holgerkoser** [comment]
> also remove `"clipboard": "^2.0.11",` from `package.json`

✔️

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
