### PR TITLE
Apply the upcoming changes to the AWS IAM policy

### PR DESCRIPTION
**Pull request by ialidzhikov**
Sibling PR of https://github.com/gardener/gardener-extension-provider-aws/pull/322

**Release note**:

```bugfix user
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by petersutter — APPROVED** [review]
/lgtm

thnx

**Review by grolu — APPROVED** [review]
/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Pull request merged**
