### PR TITLE
Updated the kubeconfig documentation

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
This PR updates the documentation that deals with working with kubeconfig files. It:
- updates the "Accessing the Gardener API" topic
- updates the "Project Operations" topic
- renames the "Accessing the Gardener API" file to "Automating Project Resource Management"
- renames the file from "gardener-api.md" to "automated-resource-management.md"
- adds an alias to the newly renamed file
- updates all links that reference the renamed file

The PR was created with help from @donistz.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
Updated the kubeconfig documentation
```

### CODE REVIEW

**Review by donistz — CHANGES_REQUESTED** [review]
Note: You can also manage your Gardener project resources automatically using a Gardener service account. For more information, see []  => There is no link

**Comment by n-boshnakov** [comment]
> Note: You can also manage your Gardener project resources automatically using a Gardener service account. For more information, see [] => There is no link

The issue has been resolved with the latest commit.

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
