### PR TITLE
[WIP]Enhance Dashboard with Viewers

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Add support for project.viewers to the Gardener Dashboard

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
The Gardener support Users/Groups/ServiceAccounts as part of the `Project` resource called `viewers`. Those subjects are given with read-only access to the API called.
See https://github.com/gardener/gardener/pull/1004 
**Release note**:

```improvement user
The Gardener Dashboard now supports the Project Viewers.
```

### CODE REVIEW

**Comment by vpnachev** [comment]
The very first prototype is ready
Screenshot_2019-06-17 Kubernetes Gardener

IMHO, I do not like it very much and I have another more simple idea, but let's keep this for now.

**Comment by marwinski** [comment]
Can we just ad the role (administrator/owner, viewer) to the member list?

**Comment by vpnachev** [comment]
My next idea is to add a check box `read-only` for the current members creation dialog which will simplify the integration.

**Comment by grolu** [comment]
@vpnachev Sorry that we did not react to your PR faster ... we've been blocked with other stuff until now.  Can you give an update on the status of this PR? Can we start reviewing and give you feedback or do you want to change some things beforehand?

**Comment by vpnachev** [comment]
Let's wait the new Project API https://github.com/gardener/gardener/pull/1382 to be adopted in the Dashboard. Then this PR will have to be adopted the new api, or it even might be obsolete.

**Comment by vpnachev** [comment]
I am closing this PR.

**Pull request closed without merging**
