### PR TITLE
Updated the Gardener API documentation - Rebased PR

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
This PR brings the changes from PR #1333 into a rebased version of the branch due to conflicts. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Content already approved in PR #1333 
**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Review by petersutter — APPROVED** [review]
/lgtm

**Comment by petersutter** [comment]
@n-boshnakov rebase is required again

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
