### PR TITLE
including the iss parameter in server code exchange

### PR DESCRIPTION
**Pull request by lekev**
**What this PR does / why we need it**:
This Pull Request adds compatibility for the Authorization Server Issuer Identification extension as specified in RFC 9207. This extension requires the inclusion of the iss parameter, received from the Authorization Response, in the token request.
**Which issue(s) this PR fixes**:
Implementing this change resolves the "iss missing from the response" error that authorization servers using this extension may encounter.

**Special notes for your reviewer**:

**Release note**:

``` 
NONE
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @lekev for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by holgerkoser** [comment]
Thank you for submitting this pull request. We encountered the same issue today and addressed it in a recent commit. Could you please update your pull request to align with the approach we took in this commit: https://github.com/gardener/dashboard/pull/1724/commits/d752df12003dc165dcb2d75ca98b7ad3333674e7

**Comment by holgerkoser** [comment]
The build fails because there are two `eslint` errors. Cloud you please run
```
yarn workspace @gardener-dashboard/backend lint --fix
```
in the root folder of the dashboard repo.

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
