### PR TITLE
user metrics

### LINKED ISSUE #150: Add custom user metrics to dashboard
Custom metrics, specifically user metrics, need to be added to the dashboard. Right now only default metrics are being generated.

### PR DESCRIPTION
**Pull request by wyb1**
**What this PR does / why we need it**:
Added garden_users_total to prometheus metrics.

**Which issue(s) this PR fixes**:
Fixes #150

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Added garden_users_total to prometheus metrics.
```

### CODE REVIEW

**Comment by petersutter** [comment]
I think this can be also mentioned in the release notes, with operator as target

**Comment by petersutter** [comment]
as just discussed we put this pull request on hold as there is a discussion on creating a metrics exporter, then these metrics would move into this new component

**Comment by petersutter** [comment]
@wyb1 @dkistner is this PR obsolete with https://github.com/gardener/gardener-metrics-exporter? if yes I would suggest to close it

**Comment by dkistner** [comment]
Right we can close this PR because the functionality is integrated into the `gardener-metrics-exporter`.

**Pull request closed without merging**
