### PR TITLE
Update the Alicloud RAM policy

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind enhancement

https://github.com/gardener/gardener-extension-provider-alicloud/pull/281 updates the Alicloud RAM policy, but this update is not reflected to the policy maintained in the dashboard.

**Release note**:

```bugfix user
NONE
```

### CODE REVIEW

**Review by jia-jerry — APPROVED** [review]
Thank you for the amend.

**Review by jia-jerry — APPROVED** [review]

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
