### PR TITLE
Fixed JS error caused by vue-lazyload

### LINKED ISSUE #440: JS Console error when Popper gets destroyed
If you open and close a popper anywhere on the application, this will result in a JS cosole error. See attached screenshot.

Screen Shot 2019-07-29 at 15 50 50

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
This fixes JS Console errors
```
item.destroy is not a function
````
caused by vue-lazyload plugin.

There is already a fix merged for this issue (https://github.com/hilongjw/vue-lazyload/pull/381) however, not yet released. I downgraded the plugin for now until there is a new release available.

**Which issue(s) this PR fixes**:
Fixes #440 

**Special notes for your reviewer**:

**Release note**:

```improvement user

```

### CODE REVIEW

**Comment by petersutter** [comment]
just tested this branch, I still get the error

**Comment by grolu** [comment]
Did you run
```
npm i
```
before testing?

**Comment by petersutter** [comment]
yes just tried it again to be 100% sure

**Comment by grolu** [comment]
sorry for asking ... jsut wanted to be sure. strange I will test again

**Comment by grolu** [comment]
I also still get the errors. Don't know why I didn't experienced them last time. We need to re-check this.

**Comment by petersutter** [comment]
can you reset the changes in the backend coding?

**Pull request merged**
