### PR TITLE
Remove docforge from repo

### PR DESCRIPTION
**Pull request by Kostov6**
**What this PR does / why we need it**:
As we now use a central manifest docforge per repo is no longer needed

**Which issue(s) this PR fixes**:
Missing part of https://github.com/gardener/documentation/issues/431

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@Kostov6 maybe you can also link that section in the central manifest to prove that everything is moved to the central manifest and this change won't cause issues?

/invite @petersutter

**Comment by Kostov6** [comment]
https://github.com/gardener/documentation/blob/b6c20b98a09e5291f3f0804a8473cfd6ad8c0be6/.docforge/documentation/documentation.yaml#L93-L101

**Comment by ialidzhikov** [comment]
Due to the failing `check-docforge` step it does not execute execute the other required steps. See https://concourse.ci.gardener.cloud/builds/297954497

@Kostov6 , can we split this change to 2 change. One that removes the step from the pipeline definition, and then the rest of the clean up. You can raise 1 PR that removes the step from the pipeline definition. Once this PR is merged, you can rebase this one and we can get this one in.

**Comment by petersutter** [comment]
> @Kostov6 , can we split this change to 2 change. One that removes the step from the pipeline definition, and then the rest of the clean up. You can raise 1 PR that removes the step from the pipeline definition. Once this PR is merged, you can rebase this one and we can get this one in.

@Kostov6 are you still planning to split this PR as suggested?

**Comment by Kostov6** [comment]
https://github.com/gardener/dashboard/pull/1900

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@petersutter , can we now merge this one?

**Pull request merged**
