### PR TITLE
Remove "© YYYY" from the footer

### PR DESCRIPTION
**Pull request by berendt**
The "© YYYY" note in the footer offers no added value and can be removed without worry.

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @berendt for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
