### PR TITLE
OpenID Connect Improvements

### LINKED ISSUE #976: Implement OIDC Token Refresh (Drop Dex)
# Stories
- As provider I want a secure and minimal landscape setup (minimal helps with security but also with maintainability as there are fewer components). 

# Motivation
We need to implement OIDC token refresh in the Gardener Dashboard backend to support OIDC providers with short token lifetimes. This allows us to get rid of Dex for these cases. Short token lifetimes is also a preparation to get rid of cookies.

# Acceptance Criteria
- [ ] Implement OIDC token refresh #1246
- [ ] Remove Dex from charts (check with community and landscaper component) 
- [ ] Migrate from cookie to header based authentication mechanism #1259

### PR DESCRIPTION
**Pull request by holgerkoser**
**What this PR does / why we need it**:
##### Refresh Token
[OpenID Connect](https://datatracker.ietf.org/doc/html/rfc7636) defines the `offline_access` scope value to request a `refresh_token` in addition to the `id_token` which allows to use OIDC provider with short `id_token` lifetimes. With this PR we support the usage of scope `offline_access`. Typically the `refresh_token` is an opaque token and not a JWT with `exp` claim. But the `refresh_token` has a limited lifetime. If the `refresh_token` is used to refresh an `id_token` a new `refresh_token` is returned and the old `refresh_token` can not be used once again. Therefore the client must check if an `id_token` will expire soon and refresh the `id_token` if necessary. Since the process can be repeated again and again we recommend to configure and absolute `sessionLifetime` that stops the automatic refresh process and forces a logout if the the lifetime of a session exceeds this limit. 
 
To enable this feature the operator has to configure the scope in the chart values:
```yaml
oidc:
  scope: "openid email groups profile offline_access"
  sessionLifetime: 86400 # 1 day
```
 
##### Authorization Code Flow + PKCE
Currently all downloaded user kubeconfigs contain a `client_secret`. With this PR we support the [PKCE flow](https://datatracker.ietf.org/doc/html/rfc7636) for the OIDC client used by the dashboard itself as well for the public client used for the downloaded kubeconfig. In order to remove the `client_secret` from the downloaded kubeconfig the operator needs to force the usage the PKCE flow for the public client. The PKCE flow will be enabled by default if no `clientSecret` is given in the values.
```yaml
oidc:
  ...
  public:
    clientId: 'my-public-client-id'
    # clientSecret: 'my-public-client-secret'
``` 

It is also possible to force PKCE flow for the client used by the dashboard but the client_secret is still required.
```yaml
oidc:
  clientId: 'my-internal-client-id'
  clientSecret: 'my-internal-client-secret'
  usePKCE: true
``` 

#####  Changes in socket.io connection handling
Since it is not possible to refresh the JWT for an open [socket.io](https://socket.io) connection we close the underlying websocket connection from the server side once the JWT is expired. The client will automatically refresh the token and reconnect with the new JTW. The initial data fetch for a new or resynchronized subscription is done via HTTP.

##### Added Vue `api` plugin
Makes all `api` function available on Vue instances. The plugin intercepts all api requests and refreshes the JWT if necessary.

##### Added Vuex `localstorage` plugin
Synchronizes the browser localstorage with the corresponding Vuex module.

##### Added a Vue `logger` plugin
The logLevel of this logger can be modified by the localstorage property `global/log-level`.

##### Added a settings page
The settings page currently is only visible in developer mode. It can be enabled by setting the the localstorage property `global/developer-mode` to the value `enabled`. The logLevel can be changed on this page.
 
**Which issue(s) this PR fixes**:
Fixes #976 #984

**Special notes for your reviewer**:

**Release note**:

```feature operator
Added support for OIDC refresh tokens. This allows an operator to configure short `id_token` lifetimes. 
```

```feature operator
Added support for PKCE flow to the internal and the public OIDC client. This allows an operator to configure the the public client without a `client_secret`. 
```

### CODE REVIEW

**Comment by petersutter** [comment]
the shootInfo is not fetched anymore https://github.com/gardener/dashboard/pull/1277/files#diff-0c36ce15651c51795b411359e8caaf5af7960c82674b4f2015b8dd5f480fde2cL1430-L1443 . The kubeconfig is then not displayed 

```js
  subscribeShootAcknowledgement ({ commit, dispatch, state, getters }, object) {
    if (object.kind === 'Shoot') {
      commit('shoots/HANDLE_EVENTS', {
        rootState: state,
        rootGetters: getters,
        events: [{
          type: 'ADDED',
          object
        }]
      })
      const fetchShootAndShootSeedInfo = async ({ metadata, spec }) => {
        const promises = [dispatch('getShootInfo', metadata)]
        const seedName = spec.seedName
        if (getters.isAdmin && !getters.isSeedUnreachableByName(seedName)) {
          promises.push(dispatch('getShootSeedInfo', metadata))
        }
        try {
          await Promise.all(promises)
        } catch (err) {
          console.error('Failed to fetch shoot or shootSeed info:', err.message)
        }
      }
      fetchShootAndShootSeedInfo(object)
    }
```

**Comment by petersutter** [comment]
not necessarily related to this PR, but is the clientSecret really required https://github.com/gardener/dashboard/blob/master/charts/gardener-dashboard/templates/secret-oidc.yaml#L19 ?

**Comment by holgerkoser** [comment]
> not necessarily related to this PR, but is the clientSecret really required https://github.com/gardener/dashboard/blob/master/charts/gardener-dashboard/templates/secret-oidc.yaml#L19 ?

Since our backend application is not deployed publicly (on mobile device or a SPA or ...) the secret can be kept secure. It makes sense to require a secret I think even if it could be removed since we now have PKCE flow also in the backend.

**Comment by holgerkoser** [comment]
> the shootInfo is not fetched anymore https://github.com/gardener/dashboard/pull/1277/files#diff-0c36ce15651c51795b411359e8caaf5af7960c82674b4f2015b8dd5f480fde2cL1430-L1443 . The kubeconfig is then not displayed
> 
> ```js
>   subscribeShootAcknowledgement ({ commit, dispatch, state, getters }, object) {
>     if (object.kind === 'Shoot') {
>       commit('shoots/HANDLE_EVENTS', {
>         rootState: state,
>         rootGetters: getters,
>         events: [{
>           type: 'ADDED',
>           object
>         }]
>       })
>       const fetchShootAndShootSeedInfo = async ({ metadata, spec }) => {
>         const promises = [dispatch('getShootInfo', metadata)]
>         const seedName = spec.seedName
>         if (getters.isAdmin && !getters.isSeedUnreachableByName(seedName)) {
>           promises.push(dispatch('getShootSeedInfo', metadata))
>         }
>         try {
>           await Promise.all(promises)
>         } catch (err) {
>           console.error('Failed to fetch shoot or shootSeed info:', err.message)
>         }
>       }
>       fetchShootAndShootSeedInfo(object)
>     }
> ```

I have fixed this with commit [7435245](https://github.com/gardener/dashboard/pull/1277/commits/7435245ee650f783107c0c8c0f710b14470bfd3f)

**Comment by holgerkoser** [comment]
This pull request is replaced by #1297

**Pull request closed without merging**
