### PR TITLE
Handle unreachable seeds in terminal bootstrap logic

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
Handle unreachable seeds in terminal bootstrap logic

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
enhancement to https://github.com/gardener/dashboard/pull/831

**Release note**:

```improvement user

```

### CODE REVIEW

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Comment by grolu** [comment]
lgtm. Do we want to add a release note?

**Comment by petersutter** [comment]
we have one in https://github.com/gardener/dashboard/pull/831 that should cover this

**Pull request merged**
