### PR TITLE
Allow update of roles for foreign serviceaccounts

### LINKED ISSUE #1350: Update of foreign service accounts not possible
**What happened**:
It is not possible to change the roles of a foreign serviceaccount in the dashboard. It looks like an existing serviceaccount is always assumed to be in the project itself and not invited from a foreign project. If try to update a foreign serviceaccount an error message occurs.

Screenshot 2022-11-17 at 14 45 44
If a serviceaccount with the same name exists in the project, the wrong serviceaccount is updated.

**What you expected to happen**:
It should be possible to also update the roles of a foreign serviceaccount.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by holgerkoser**
**What this PR does / why we need it**:
With this PR it is possible to update the roles of an existing foreign serviceaccount in a project. The description of a foreign serviceaccount cannot be edited anymore.

**Which issue(s) this PR fixes**:
Fixes #1350

**Special notes for your reviewer**:

**Release note**:

```bugfix user
With this PR it is possible to update the roles of an existing foreign serviceaccount in a project 
```

### CODE REVIEW

**Review by petersutter — APPROVED** [review]
/lgtm

however I have noticed that when removing all roles of a foreign service account no error is shown and after a reload on the UI it also disappears from the list. We should improve this (create new issue?)

**Comment by holgerkoser** [comment]
> however I have noticed that when removing all roles of a foreign service account no error is shown and after a reload on the UI it also disappears from the list.

Created issue #1356

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
