### PR TITLE
If provided, use config.clusterIdentity to build the gardenlogin kubeconfig

### LINKED ISSUE #1415: config.clusterIdentity is not used in gardenlogin kubconfig
**What happened**:
The dashboard has a clusterIdentity setting to "overwrite" what gets fetched from the configmap kube-system/cluster-identity otherwise. This works for the frontend and is correctly shown in the Gardenlogin "info" card.

But in the gardenlinux kubeconfig copy/show contents, ONLY the value from configmap kube-system/cluster-identity is used, NOT the setting.

 A user that follows the instructions as given won't have sucess with the provided gardenlogin kubeconfig.

**What you expected to happen**:
The gardenlinux kubeconfig to contain the gardenClusterIdentity set in the dashboard config.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy dashboard with config clusterIdentity: foo to a gardener with cluster-identity bar. The info text will show foo, the kubeconfig will show bar.

**Environment**:
Gardener 1.63.1, Dashboard 1.66.0

### PR DESCRIPTION
**Pull request by j2L4e**
**What this PR does / why we need it**:
If a clusterIdentity "override" via config.yaml is present, it should be honored in the gardenlogin kubeconfig presented to the user.
**Which issue(s) this PR fixes**:
Fixes #1415 

**Special notes for your reviewer**:

**Release note**:
```
No longer ignores clusterIdentity override when building gardenlogin kubeconfig
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @j2L4e for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by grolu — APPROVED** [review]
/lgtm

**Comment by petersutter** [comment]
thanks @j2L4e , would you mind to write a test for this fix? You can temporarily set the `clusterIdentity` for your test on the test config. Search for `Object.defineProperty(config` to see how it was done in other tests.

Also the build fails with
```
#24 [dashboard-builder 1/8] RUN yarn workspace @gardener-dashboard/backend run lint
#24 sha256:ba5280de84546cdef7a8ce26620188239f15a642abe27bb309c176dd0d1b0f37
#24 8.108 
#24 8.108 /app/backend/lib/services/shoots.js
#24 8.108   472:40   error  Missing space before function parentheses  space-before-function-paren
#24 8.108   473:3    error  Expected space(s) after "if"               keyword-spacing
#24 8.108   477:103  error  Extra semicolon                            semi
#24 8.108 
#24 8.108 ✖ 3 problems (3 errors, 0 warnings)
#24 8.108   3 errors and 0 warnings potentially fixable with the `--fix` option.
#24 8.108 
#24 ERROR: executor failed running [/bin/sh -c yarn workspace @gardener-dashboard/backend run lint]: exit code: 1
------
 > [dashboard-builder 1/8] RUN yarn workspace @gardener-dashboard/backend run lint:
------
executor failed running [/bin/sh -c yarn workspace @gardener-dashboard/backend run lint]: exit code: 1
Traceback (most recent call last):
  File "<string>", line 193, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('docker', '--config', '/tmp/tmppkghq6zy', 'build', '--progress', 'plain', '--build-arg', 'EFFECTIVE_VERSION=1.68.0-dev-45aa7dd3b8545c6b7524774e5a2a9f0951b207e7', '--target', 'dashboard', '--tag', 'eu.gcr.io/gardener-project/gardener/dashboard:1.68.0-dev-45aa7dd3b8545c6b7524774e5a2a9f0951b207e7', '--file', 'master-image/Dockerfile', 'master-image/')' returned non-zero exit status 1.

```

**Comment by j2L4e** [comment]
Sure. Is this what you had in mind?

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by grolu — APPROVED** [review]
/lgtm

**Pull request merged**
