### PR TITLE
Terminal Bootstrap: Skip seed with missing secretRef

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
With the introduction of the [gardenlet](https://github.com/gardener/gardener/releases/tag/v0.33.0) the `spec.secretRef` is optional on the seed resource.
If it is missing, the shoot cannot be bootstrapped and needs to be skipped.

In case a shoot is used as seed, the flag `with-secret-ref` has to be added to the `shoot.gardener.cloud/use-as-seed` annotation so that the `spec.secretRef` is set on the seed.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user

```

### CODE REVIEW

**Comment by grolu** [comment]
what about asking the gardener team if this change can be reverted. In addition, how do we handle this when fetching information from the backend for the cluster detail page? Do we also log an error about missing secret in this case or only an unspecific seed not reachable error?
Otherwise lgtm

**Comment by petersutter** [comment]
After I thought about it again I think it's just a documentation issue.
@rfranzke is the with-secret-ref flag documented when setting up a seed from a shoot? As long as the seed is reachable from the dashboard `spec.secretRef` is required for the dashboard.

@grolu for the details page we log the error `Failed to retrieve information using seed core client`

**Comment by grolu** [comment]
@petersutter wouldn't it make sense to log a similar message in case retrieving information from the seed fails for this reason, e.g. `Failed to retrieve information using seed core client as 'spec.secretRef' on the seed is missing. In case a shoot is used as seed, add the flag \`with-secret-ref\` to the \`shoot.gardener.cloud/use-as-seed\` annotation`

**Comment by grolu** [comment]
@rfranzke @petersutter Yes, it is ok that the field is optional. But it must be clear that this field is required for the dashboard to work properly.

**Comment by petersutter** [comment]
> @petersutter wouldn't it make sense to log a similar message in case retrieving information from the seed fails for this reason, e.g. `Failed to retrieve information using seed core client as 'spec.secretRef' on the seed is missing. In case a shoot is used as seed, add the flag with-secret-ref to the shoot.gardener.cloud/use-as-seed annotation`

yes makes sense I will also add a proper log message here

**Comment by rfranzke** [comment]
It's not documented yet, should probably be done as part of https://github.com/gardener/gardener/issues/2181

**Pull request merged**
