### PR TITLE
Ui improvements

### LINKED ISSUE #263: Sort clusters by version
The recent [K8s Security Announcement](https://groups.google.com/forum/#!topic/kubernetes-announce/GVllWCg6L88) made it necessary to sort the long list of clusters by version to identify the clusters which have a vulnerable version and need to be updated or upgraded. Sorting by version is currently possible in the Gardener Dashboard but not in the desired way. An alternative would be to enter a version in the search field and get a filtered list.

### LINKED ISSUE #266: Dashboard is very slow and unresponsive when listing all clusters
**Dashboard is very slow and unresponsive when listing all clusters.**
The problem is observed only on Canary. It takes ~18s(measured from 10 attemps) to load all clusters regarless of their state. Clicking on the search panel after that is still very slow. Sometimes the Dashboard freezes at all, even receiving "something went wrong". 

**How to Reproduce:**
1. Log into Canary Landscape Dashboard
2. Select ALL PROJECTS
3. Unselect ''Show only clusters with issues'
4. Click on search panel

### PR DESCRIPTION
**Pull request by grolu**
**What this PR does / why we need it**:
This PR bundles a bunch of UI Improvements, including improved sorting by version and searching the cluster list. Moreover it introduce (client-side) paging to improve performance when dealing with large cluster lists. Other minor UI fixes / improvements

**Which issue(s) this PR fixes**:
Fixes #266, Fixes #263

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed: Sort by version in cluster list
```
```noteworthy user
Improved search in cluster list: You can now search for name, project, infrastructure, created by, purpose, Kubernetes version and journal labels
```
```noteworthy user
Introduced client-side paging on the "all projects" list to improve rendering performance of large cluster lists
```
```improvement user
Fixed: Readiness tag issues
Cursor pointer did not work due to latest Vuetify updates
Always use shortened name for readiness tags
Show full name as tooltip
```
```improvement user
Fixed: Namespace instead of real project name was shown in "all projects" cluster list
```
```improvement user
Fixed: Some alignment issues in help and about menu
```

### CODE REVIEW

**Comment by petersutter** [comment]
on reset, reset also page size

**Comment by petersutter** [comment]
sort by version does not work

**Comment by petersutter** [comment]
`NaN-NaN of 1`
if table is empty

**Comment by grolu** [comment]
This is probably an issue with the datatable component itself; I am unable to reproduce and I do not control the values displayed

**Pull request merged**
