### PR TITLE
Moved Architecture topic to development folder

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
This PR moves the Architecture topic from its own folder to the development folder. The reasons for this is the unnecessary nesting that leads to making the documentation harder to access on the website and as a whole. 

Screenshot 2024-05-09 102003

The topic will still be categorized with the correct persona and will still appear as the first topic in the Dashboard section. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by petersutter** [comment]
@n-boshnakov a check has failed for this PR

>  Error: 1 error occurred:
> 	* cannot resolve nodeSelector relative path https://github.com/gardener/dashboard/tree/check-manifest/docs/architecture in node /architecture and manifest https://github.com/gardener/dashboard/blob/check-manifest/.docforge/manifest.yaml

**Comment by n-boshnakov** [comment]
> @n-boshnakov a check has failed for this PR
> 
> > Error: 1 error occurred:
> > 
> > * cannot resolve nodeSelector relative path https://github.com/gardener/dashboard/tree/check-manifest/docs/architecture in node /architecture and manifest https://github.com/gardener/dashboard/blob/check-manifest/.docforge/manifest.yaml

Alright, it took me some time, but I finally found out the issue. It should be fixed with the latest commit. 

Could I ask you to rebase the branch again and retest?

**Comment by petersutter** [comment]
same error..

**Comment by n-boshnakov** [comment]
> same error..

Sorry, I had accidentally removed the wrong part of the manifest. I will fix this in the next commit.

**Comment by n-boshnakov** [comment]
@petersutter Everything should be fixed now. Could you re-review the PR?

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Review by petersutter — APPROVED** [review]
/lgtm

**Pull request merged**
